<!-- Här skrivs all HTML till sidan -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <link rel="stylesheet" type="text/css" href="style.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<template id="loginFormTemplate">
  <h2>Login</h2>
  <p>Här ska login formuläret vara</p>
  <label>Användarnamn: </label>
  <br>
    <input type="text" name="username" class="login">
    <br> <br>
    <label>Lösenord: </label>
    <br>
    <input type="password" name="password" class="login">
    <br> <br>
    <input type="submit" value="Logga in" class="index-button">
</template>
<template id="registerFormTemplate">
  <br>
  <h2>Register User</h2>
  <p>Här ska ska man kunna registrera en användare</p>
    <label>Användarnamn: </label>
    <br>
    <input type="text" name="username" class="login">
    <br> <br>
    <label>Lösenord: </label>
    <br>
    <input type="password" name="password" class="login">
    <br> <br>
    <input type="submit" value="Logga in" class="index-button">
</template>

  <div class="container">
  <header>
    <h1><?=$title?></h1>
  </header>
  
  <main>

  </main>
  </div>
  <script type="text/javascript" src="main.js"></script>
</body>
</html>
